export { default as EditorTemplate } from './Editor'
export { default as ListTemplate } from './List'
export { default as PageTemplate } from './Page'
export { default as PostTemplate } from './Post'
export { default as LoginTemplate } from './Login'
export { default as SignUpTemplate } from './SignUp'
